<41번> 학사관리시스템에 아래 학점관리 테이블을 생성하시오.

CREATE TABLE hakjum (
    grade       CHAR(2)     NOT NULL,
    min_point   NUMBER(3)   NOT NULL,
    max_point   NUMBER(3)   NOT NULL
);

<42번> 학점관리 테이블에 성적 기준표를 삽입하시오,
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('A+',96,100);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('A0',90,95);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('B+',85,89);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('B0',80,84);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('C+',75,79);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('C0',70,74);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('D+',65,69);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('D0',60,64);
    INSERT INTO HAKJUM(GRADE,MIN_POINT,MAX_POINT)
        VALUES('F',0,59);

<43번> (연속)학사관리시스템에서 수강학생들의 성적을 학점으로 나타내시오.
SELECT a.STD_NO 학번, a.STD_NAME 학생명, b.SUB_NAME 과목명, c.CLS_SCORE 점수, d.GRADE 학점
FROM STUDENT a, SUBJECT b, CLASS c, HAKJUM d
WHERE (a.STD_NO = c.STD_NO) and (b.SUB_CD = c.SUB_CD)
        AND c.CLS_SCORE BETWEEN d.MIN_POINT AND d.MAX_POINT
ORDER BY c.CLS_SCORE DESC;





